version: "3.1"
   
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django-user
      - POSTGRES_PASSWORD=Qq123456!
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./code:/code
    depends_on:
      - db
  proxy:
    image: nginx
    restart: always
    volumes:
      - ./server/nginx/conf.d:/etc/nginx/conf.d
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/certs:/etc/ssl/certs
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - web
