version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./code:/code
    environment: # read about secrets
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
  proxy:
    image: nginx
    volumes:
      - ./server/nginx/conf.d:/etc/nginx/conf.d
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server/certs:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
